# Generated by Django 5.0.6 on 2024-07-02 13:35

import django_fast_iprestrict.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_fast_iprestrict', '0011_correct_ruleratelimitgroup_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleratelimit',
            name='rate',
            field=models.CharField(help_text='Set to "inherit" to use the provided rate (when set to "inherit" ratelimit is ignored in middleware and without a provided rate).Set to "none" to not provide a rate.', max_length=10, validators=[django_fast_iprestrict.validators.validate_rate]),
        ),
    ]
